### ISSUE TITLE
Hello! What does the 'intention' attribute mean? What's the difference of "intention" and "cross"?

### ISSUE THREAD

**Issue by fanfanfanf** [aras62/PIE#1]

**Comment by aras62** [comment]
Hi, Intention tells you how likely the pedestrian "Wants" to cross. For example, a pedestrian might be standing at the curb waiting for the bus, so the intention is very low. Someone with no intention of crossing will definitely not cross and someone with intention of crossing may/may not cross the road. For more information, please refer to the paper  "PIE: A Large-Scale Dataset and Models for Pedestrian Intention Estimation and Trajectory Prediction".
