### ISSUE TITLE
Pedestrian intention statistics different in web and code

### ISSUE THREAD

**Issue by javierlorenzod** [aras62/PIE#11]
Hello!

Today I used your function [`get_data_stats`](https://github.com/aras62/PIE/blob/289c28b39ed422885523a5262c509ce23313571f/pie_data.py#L532) and I found that the number of pedestrians is different from the one in the webpage of the dataset. I checked with an improvised loop, and I obtain the same results as in the function, so maybe it is not updated in the webpage. 

I attached a screenshot at the end. The results from the function are the following:

> crossing:
>      crossing: 519
>      irrelevant: 468
>      not-crossing: 855

![pie_stats_webpage](https://user-images.githubusercontent.com/6094231/93353867-b19ffd80-f83c-11ea-8b97-bc4a99100fe0.PNG)

Also, the total number in the function output is the same as in the web.

If there is something wrong with my findings, please tell me, it will help my research.

Hope it helps!

**Comment by aras62** [comment]
Hi, 
Thank you for bringing that to our attention. The stats on the webpage are incorrect. They were generated based on an old database. We also made a change to update how the statistics in the interface is generated. Please use the statistics again with the new changes we made. We will shortly update the info on the website as well.

Thanks

**Comment by javierlorenzod** [comment]
Your welcome, thanks for sharing your work with the research community!
