### ISSUE TITLE
Question about camera height

### ISSUE THREAD

**Issue by podragonwer** [aras62/PIE#12]
Hello,
do you have information about the height of the camera when it was recorded?
In the paper, it is only said that the camera was placed "below the rear-view mirror".
I would really appreciate if you could provide more information.
Thank you.

**Comment by ykotseruba** [comment]
Hi,
the camera height is 1270 mm and the pitch is -10 degrees. I added these to camera parameters JSON too.

**Comment by podragonwer** [comment]
Thank you!
