### ISSUE TITLE
Mean and standard deviation of images in dataset

### ISSUE THREAD

**Issue by javierlorenzod** [aras62/PIE#17]
Hello:

I have been searching through the code and I have not found the mean and standard deviation of the dataset images (per channel). Do you have calculated them, by any chance? If so it would help me a lot.

Thanks!

**Comment by ykotseruba** [comment]
Hi, 
Unfortunately, we did not calculate the mean and std of the images in the dataset. Perhaps, you could use this script [https://gist.github.com/jdhao/9a86d4b9e4f79c5330d54de991461fd6](https://gist.github.com/jdhao/9a86d4b9e4f79c5330d54de991461fd6).

**Comment by javierlorenzod** [comment]
Ok, thanks for the info and the gist!
