### ISSUE TITLE
Is there a detailed explanation of the vehicle annotations?

### ISSUE THREAD

**Issue by Yijun88** [aras62/PIE#19]
Hi Amir,

First of all, excellent work on the PIE dataset! It provides a very detailed annotations for both intention and trajectory prediction tasks. But I'm a bit lost in the vehicle annotations. Can I ask:

1) What is the difference between the yaw pitch roll and gyroX, Y, Z? (I assume both of them are rotations)
2) How do accX, accY, and accZ get calculated? What unit are they measured in?

Generally, I was trying to calculate the ground truth relative camera pose (yaw, pitch, roll, x, y, z) between the frames but couldn't wrap my head around those vehicle annotations. 

Best,
Yijun

**Comment by aras62** [comment]
Hi Yijun,

Thank you for using our dataset. The difference between the two is the frame of reference. Yaw, pitch and roll is read from the vehicle sensor whereas gyro and acc data is read from the camera’s internal sensors. As for units, I am not 100% as I could not find sensor specifications for the camera. My guess for acc  is m/s^2.

**Comment by Yijun88** [comment]
Hi Amir,

Thanks for your response. I will try to verify/use the vehicle annotations for relative camera pose generation and update in the same pose if I have any new info.
