### ISSUE TITLE
Some images are missing cannot run the model

### ISSUE THREAD

**Issue by louisnot** [aras62/PIE#20]
Hello there, I've been working on this dataset the past few weeks and I've encountered a problem during the training step. I get an error saying that a file has note been found. This file is an image from the set_01/video_01. Image 17715.png
After looking manually in my folder it is right there is such image.
To extract images from the video clips I used the shell script it took quiet a while to run but I believe it did it succesfully. 
Do you know if some errors can occur during the extraction of images from the clips? 
I'm not sure what to do now. 

Thanks in advance

**Comment by ykotseruba** [comment]
Hi,
sometimes the images may become corrupted during the extraction. If you cannot open the image, then the easiest solution is to delete it and to convert the video again or to use the python script (as explained in README). This way is faster since only the missing frame will be extracted again.
