### ISSUE TITLE
How to use the dataset to train a YOLO object detector?

### ISSUE THREAD

**Issue by Christoph9402** [aras62/PIE#22]
Hello, I want to train a custom object detection using the PIE Dataset, but I want to train a yolo, which does not use the xml format for annotations. I have 2 Questions:
1) How can I convert the annotations to be used with yolo (.txt)? I need the Bounding Box positions, as well as the attribute, if the person is walking or standing (for 2 different classes in detection--> "person standing" or "person walking"). Is there an easy way of converting the annotations for my use, or would you suggest to use another object detector?
2) Furthermore I want to extract the vehicles heading direction and current speed, so that I have a .csv file for each video file, in which each row represents a frame of the video with the 2 values.
I am quite confused by the complexity of the annotaions. Any help is appreciated, thanks :)

**Comment by ykotseruba** [comment]
Hi @Christoph9402,
1) You can try loading the annotations into (CVAT)[https://github.com/openvinotoolkit/cvat] and exporting them in YOLO format.
2) Heading direction and speed are in `annotations_vehicle.zip`, which contains one xml per video with direction, current speed and more. A simple Python script to parse those and output them to csv should do it or you can load each xml file into Excel (or LibreOffice Calc) (see (link)[https://www.spreadsheetweb.com/how-to-import-xml-files-into-excel/]).

**Comment by Christoph9402** [comment]
Thank you for your answer! I am going to try the tool for converting tomorrow and keep you updated. Your Idea to load the xml files into Excel was just what i was looking for :)

**Comment by Christoph9402** [comment]
I have an additional question regarding the dataset. I downloaded the Clips and Annotations and have the following folder structure:
```
PIE_dataset
    annotations
        set01
        set02
        ...
    PIE_clips
        set01
        set02
        ...
```
I now place the files `pie_data.py` ,` split_clips_to_frames.sh` and a python file` extract_images.py` which includes these lines of code, since i only want to save images with bounding boxes
```
from pie_data import PIE
pie_path = 'C:/Users/Chris/Documents/Uni/Studienarbeit/Dataset/PIE_dataset'
imdb = PIE(data_path=pie_path)
imdb.extract_and_save_images(extract_frame_type='annotated')
```
inside the PIE_dataset folder. When I run `extract_images.py`, I get the following error message:
```
from scipy import optimize
  File "C:\Users\Chris\anaconda3\envs\studienarbeit_env\lib\site-packages\scipy\optimize\__init__.py", line 398, in <module>
    from ._nnls import nnls
ImportError: DLL load failed: The specified module could not be found
```

What did I do wrong? How can I fix this? Also, is the folder structure wrong for running the script?

**Comment by ykotseruba** [comment]
The folder structure seems ok. Based on the error message, something may be wrong with your scipy installation. I don't use conda or Windows so I don't know how to resolve it. Try googling the error message or check issues in conda and scipy githubs.

**Comment by Christoph9402** [comment]
@ykotseruba Thank you very much for your help :) I am going to find an answer to that on google
