### ISSUE TITLE
What does the bounding box coordinates mean?

### ISSUE THREAD

**Issue by doMoreCode** [aras62/PIE#23]
Hello, i dont understand the mean of  bounding box coordinates such as xbr .Is that the object before the car?

**Comment by doMoreCode** [comment]
i just want to know where are the bounding box coordinates of pedestrian. @aras62 , thanks.

**Comment by aras62** [comment]
You can find the bounding box coordinates in attributes.zip for each pedestrian's instance, there is a 4-point coordinates like this: xbr="929.18" xtl="916.82" ybr="847.11" ytl="793.32" which correspond to top-left and bottom-right corners of the bounding boxes.

**Comment by doMoreCode** [comment]
> You can find the bounding box coordinates in attributes.zip for each pedestrian's instance, there is a 4-point coordinates like this: xbr="929.18" xtl="916.82" ybr="847.11" ytl="793.32" which correspond to top-left and bottom-right corners of the bounding boxes.


emm i wanted to draw a rectangle to see which pedestrian in image, but i  got none. In my case, i use matlab  to manipulate image .(The origin of the picture is start from the upper left corner)。Should i use the camera's parameters to transfer the coordinates?@aras62

**Comment by aras62** [comment]
the coordinates in attributes are for opencv. Matlab has a different coordinate system, so you need to convert them.  I don't remember matlab one but one of the main differences can be the axis. For your second question, no you do not need to you camera parameters, the coordinates are in image plane.

**Comment by doMoreCode** [comment]
> the coordinates in attributes are for opencv. Matlab has a different coordinate system, so you need to convert them. I don't remember matlab one but one of the main differences can be the axis. For your second question, no you do not need to you camera parameters, the coordinates are in image plane.

thanks for your answer, i got it.
