### ISSUE TITLE
The Annotations cannot match images

### ISSUE THREAD

**Issue by sunyuan789** [aras62/PIE#24]
I want to see what the annotations show in the picture. So I use `generate_database()` to generate `pkl`file. But it cannot match with every images. The code is following:
```python
import cv2
a = cv2.imread('set02/video_0003/frame_821.jpg')
a = cv2.rectangle(a, (134, 802), (110, 704), (255, 0, 0), 5)
cv2.imshow('ad', a)
cv2.waitKey()
cv2.destroyAllWindows()
```
![Quicker_20220324_150132](https://user-images.githubusercontent.com/37969983/159860596-304980b6-bdf7-4a92-af91-596fe4318d12.png)
The pedestrian(2_3_194) annotation on set02/video_0003/frame_821 is [110.61,704.5,134.85,802.92].
I use opencv function of rectangele to show this, but you see it cannot match pedestrian.
Could you please tell where either the code is error or the pkl is error? Thank you for your help!

**Comment by ykotseruba** [comment]
The annotations are correct. I could not reproduce the error with your code in opencv 4.2. Below is the result I am getting, the bounding box matches the pedestrian: 
![821](https://user-images.githubusercontent.com/4388939/159937743-9a029234-66d9-4c1c-a24e-848b7673a926.png)
.

**Comment by sunyuan789** [comment]
I am sorry to bother you sir. I tried generating *pkl again, but I get a same result. After searching annotations/set02/video_0003_annt.xml, I found the following annotation.
![tmp425C](https://user-images.githubusercontent.com/37969983/160037113-98c8616a-8d8f-4933-8717-10fde0b11d82.png)
It seems like an annotation of pedestrian with id 2_3_194 is [110.61,704.50,134.85,802.92].
Likewise, the annotation in your picture seems not to match pedestrian also. 
It may correct effect of annotation should be the following picture.
![c](https://user-images.githubusercontent.com/37969983/160037700-dc1e3b0f-6228-450c-a3a3-7fd13814b340.jpg)
**The dataset might get errors when downloading or it needs another operation to process data.**
The version of opencv-python is 4.5.5.64 in my packages.
Could you please send me a correct file(pie_database.pkl) address?
Thank you for your help!

**Comment by sunyuan789** [comment]
I am so sorry sir. It's all my fault. I use software(potplayer) to capture screen present picture which saved pixy with 1608*904 instead 1920*1080. I made a giant mistake. Sorry to bother you sir. Your repos are unbelievably valuable!

**Comment by ykotseruba** [comment]
No worries, I'm glad you were able to resolve the issue.
