### ISSUE TITLE
Annotation 'designated'

### ISSUE THREAD

**Issue by MoritzLennartz** [aras62/PIE#25]
Hello, 

in the python interface in the function generate_database() the annotation 'designated' is listed. However, this annotation is not included in the xml files and is not listed in the readme. 
Does this annotation only exist for JAAD and not for PIE?

**Comment by ykotseruba** [comment]
Hi, you are correct, there is no 'designated' tag in PIE, instead jaywalking pedestrians are tagged with 'signalized'=n/a.

**Comment by MoritzLennartz** [comment]
Thank you very much. This has helped me a lot
