### ISSUE TITLE
Annotation 'signalized'

### ISSUE THREAD

**Issue by MoritzLennartz** [aras62/PIE#26]
Hello, 

Can you explain to me in more detail how the annotation signalized is differentiated? I looked a bit more at the data to understand the annotations. 

I checked Set01 Video_0007 Frames 224 to 499. This person has the ID 1_4_105. 

![image](https://user-images.githubusercontent.com/64199570/169372484-3f8d9bb5-af56-4b9f-89a7-b8306ec2c427.png)

Why is the annotation 'signalized' = 3 for this pedestrian? I can't see any signal in the frames. Can you explain this to me?

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/64199570/169372572-f62ca212-a5ee-498c-802b-14fcd32c9708.png">

Thank you very much for your help! 

Many greetings
Moritz

**Comment by ykotseruba** [comment]
"Signal" attribute includes traffic lights and stop signs since they both control the intersection and require the driver to stop. We combined them into a single label for simplicity. In the sample you showed there is a stop sign at the intersection. I have updated the readme.

**Comment by MoritzLennartz** [comment]
Thank you very much. This has helped me a lot
