### ISSUE TITLE
about video to images

### ISSUE THREAD

**Issue by aoteman233** [aras62/PIE#27]
hi,

Thank you very much for your excellent work

Where should this code be used when generating images?

from pie_data import PIE
pie_path = <path_to_the_root_folder>
imdb = PIE(data_path=pie_path)
imdb.extract_and_save_images(extract_frame_type='annotated')

**Comment by ykotseruba** [comment]
We used it as a standalone python script to extract images from videos.

**Comment by aoteman233** [comment]
Thank you very much
