### ISSUE TITLE
There may be an error in the pedestrian boundingbox annotation of set03video0001

### ISSUE THREAD

**Issue by githubcvcv** [aras62/PIE#29]
Hello, 
There may be an error in the pedestrian boundingbox annotation of set03video0001, 
For example, The pedestrian boundingbox of set03video0001_04349.png is [542.87, 631.34, 682.74, 1032.32], as shown in the figure:
![04349_new](https://user-images.githubusercontent.com/109346193/183393550-1ead5408-741c-46e5-a60e-37e1161a9428.png)
It can be seen from the figure that there are no pedestrians in the rectangular box. 
I checked the data of other sets, and the annotations can match correctly, but set03video0001 cannot. 
Your work is very valuable and important to me. I look forward to your reply. Thank you very much!

**Comment by ykotseruba** [comment]
Hi,
Thank you for your interest in our work. I think there might be an issue with how you are visualizing the data. Frame 4349 from set03 video 0003 is shown below with the annotation. The frame you attached looks like it is from set01 video0001.
<img width="896" alt="Screen Shot 2022-08-08 at 1 29 33 PM" src="https://user-images.githubusercontent.com/4388939/183477949-7448aa9e-d200-4d70-848a-3aa44ebe33a7.png">

**Comment by githubcvcv** [comment]
> Hi, Thank you for your interest in our work. I think there might be an issue with how you are visualizing the data. Frame 4349 from set03 video 0003 is shown below with the annotation. The frame you attached looks like it is from set01 video0001. <img alt="Screen Shot 2022-08-08 at 1 29 33 PM" width="896" src="https://user-images.githubusercontent.com/4388939/183477949-7448aa9e-d200-4d70-848a-3aa44ebe33a7.png">

Hello, 
Sorry, I made a mistake. I may have accidentally copied set01video0001 to set03 when downloading the dataset. If it were not for your help, I might never have discovered this mistake. Thank you for your help. Thank you very much!
