### ISSUE TITLE
The label does not correspond to the video picture

### ISSUE THREAD

**Issue by Serenfang** [aras62/PIE#30]
Hello author, I am numbered in the image set03\video_0005\03045.png image, using the provided coordinates (1291.6, 652.01, 1416.2, 994.3), But the drawn border does not correspond to the picture. The picture is shown below.I don't know why it doesn't match.

![$)4D4{%%BZF7$89S$Q}75BR](https://user-images.githubusercontent.com/68155266/197193661-294be14e-8476-4afc-9ce3-fcf1cc9917eb.png)

**Comment by Serenfang** [comment]
I have solved the problem, I had a small error when dividing the video into frames.

**Comment by ykotseruba** [comment]
Since the issue has been resolved, I am closing it.
