### ISSUE TITLE
what does '1_1_1' represent in annotation?

### ISSUE THREAD

**Issue by munirfarzeen** [aras62/PIE#32]
Hi, 
if you use the function data_generation(), the outputs contain a list of annotations corresponding to a video, there are labels like '1_1_1', what does this represent?
pedestrian id?

**Comment by ykotseruba** [comment]
The format of the labels is explained in the README, see Spatial Annotations section:

"Each object has a unique id in the form of `<set_id>_<video_id>_<object_id>`, e.g. pedestrian with id `1_2_50` is found in video 2 of set 1."
