### ISSUE TITLE
Extracting images clarification on README

### ISSUE THREAD

**Issue by simonescaccia** [aras62/PIE#34]
Following the 'Extracting images' paragraph, while extracting only the annotated frames, I encountered the following error:

`FileNotFoundError: [Errno 2] No such file or directory: 'annotations'`

I suggest writing in the README to unzip the annotation files first and then run the code.

**Comment by aras62** [comment]
Hi, 
Thanks for the suggestion. We added a note to the README of the annotations for unzipping.
