### ISSUE TITLE
Extract other attributes for prediction 

### ISSUE THREAD

**Issue by aalzooke** [aras62/PIE#5]
Hi Amir, 
I noticed they you only used intention_prob, trajectory and vehicle speed for prediction but what about the other attributes like standing, looking, traffic light etc. please let us know your thoughts  Thank you

**Comment by aras62** [comment]
Hi,

Other attributes can certainly be used as well to get a better sense of future actions. There are some recent works that use pedestrian activities as a way of conditioning future events.
