### ISSUE TITLE
Camera parameters

### ISSUE THREAD

**Issue by javierlorenzod** [aras62/PIE#6]
Hello!

Do you have intrinsic and/or extrinsic camera parameters available anywhere? I read your paper and the information in the repository and I did not find anything and maybe I searched in the wrong places.

Thank you!

**Comment by MoonBlvd** [comment]
Hi @javierlorenzod, I'm looking for camera parameters as well, do you have any clue? Thanks!

**Comment by aras62** [comment]
Hi, 

The camera parameters are added to the repository under camera_params folder
