### ISSUE TITLE
Annotation of vehicles are not completed?

### ISSUE THREAD

**Issue by MoonBlvd** [aras62/PIE#7]
Hi Amir,

Thank you for making this great dataset!
I'm using PIE for my research and I wanted to get trajectories of vehicles as well. I have noticed that only some of the vehicles in the videos are labelled. Does the original PIE contain all vehicle labels? If no, what is the  specific reasons that only some the vehicles are labelled? 

Thank you,
Brian

**Comment by ykotseruba** [comment]
Hi Brian,
we annotated vehicles that were relevant to the behavior of pedestrians of interest.

**Comment by MoonBlvd** [comment]
@ykotseruba Thank you for your quick response! Can you share more information about the idea of determining which vehicles in what time period are relevant to the pedestrians? According to my understanding, there could multiple pedestrians annotated in a frames, so is there a label saying which car is related to which pedestrian?

**Comment by ykotseruba** [comment]
We selected those vehicles that could potentially affect pedestrians' behaviors but there are no group labels.

**Comment by MoonBlvd** [comment]
@ykotseruba Sounds good, thank you!
