### ISSUE TITLE
_height_check function in pie_data.py is calculating the width

### ISSUE THREAD

**Issue by prateekagrawal06** [aras62/PIE#8]
Hi,

The description of the dataset says that the bounding boxes are annotated as (top left, bottom right)

According to this when calculating the height you should the y coordinates of the top left and bottom right. But in the code of _height_check you are using the x coordinates. Which actually calculates the width of the bounding boxes.

Please correct  me if I am wrong

**Comment by aras62** [comment]
Hi there, 
Thanks for bringing this to our attention. You are correct, the function was incorrectly measuring width. The issue has been rectified.
