### ISSUE TITLE
images interface

### ISSUE THREAD

**Issue by guofengpeng** [aras62/PIE#9]
hi，sir, thank you for making this great dataset!
however,my dask is too small to clip all vedio. I want to use the interface. but, due to my poor knowledge, I cannot undestand hoe to use the interface. Could you please  provide a python file which can diretly be used to make pictures?
******************************************************************************************
Alternatively, one can use the interface to only extract annotated frames (which would require 1TB space) as follows:

from pie_data import PIE
pie_path = <path_to_the_root_folder>
imdb = PIE(data_path=pie_path)
imdb.extract_and_save_images(extract_frame_type='annotated')
***************************************************************************************************

**Comment by aras62** [comment]
Hi there, 

Sorry to hear that you have difficulty with the dataset. Unfortunately, we cannot provide customized code for users. Please follow the comments and instructions in the interface code to generate partial annotations.
